// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-6JMgXDq5Ov_wV3hxykLnVujEn2YK6Y',
    appId: '1:993471989568:web:46dd14694451a80f155ca5',
    messagingSenderId: '993471989568',
    projectId: 'bookworm-app-nerqi-2025',
    authDomain: 'bookworm-app-nerqi-2025.firebaseapp.com',
    storageBucket: 'bookworm-app-nerqi-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UOi8n6-Ncazma9yKjhi2jYAg6cYxi3A',
    appId: '1:993471989568:android:185e1ffb05341e25155ca5',
    messagingSenderId: '993471989568',
    projectId: 'bookworm-app-nerqi-2025',
    storageBucket: 'bookworm-app-nerqi-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE3pUxSNwrbLDrK1WTqDXyDZU6YVj1-DE',
    appId: '1:993471989568:ios:d00f4894c17fe87b155ca5',
    messagingSenderId: '993471989568',
    projectId: 'bookworm-app-nerqi-2025',
    storageBucket: 'bookworm-app-nerqi-2025.firebasestorage.app',
    iosBundleId: 'com.example.bookworm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE3pUxSNwrbLDrK1WTqDXyDZU6YVj1-DE',
    appId: '1:993471989568:ios:d00f4894c17fe87b155ca5',
    messagingSenderId: '993471989568',
    projectId: 'bookworm-app-nerqi-2025',
    storageBucket: 'bookworm-app-nerqi-2025.firebasestorage.app',
    iosBundleId: 'com.example.bookworm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr-6JMgXDq5Ov_wV3hxykLnVujEn2YK6Y',
    appId: '1:993471989568:web:82261ee1054ce783155ca5',
    messagingSenderId: '993471989568',
    projectId: 'bookworm-app-nerqi-2025',
    authDomain: 'bookworm-app-nerqi-2025.firebaseapp.com',
    storageBucket: 'bookworm-app-nerqi-2025.firebasestorage.app',
  );

}
